name: CI

on: [push]

jobs: 
  SAST-SCAN:
    name: Run Scans
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Bandit Scan    
    - name: Install Bandit
      run: pip install bandit
    - name: Bandit Scan  
      run: bandit -ll -ii -r . -f json -o bandit-report
    # SonarQube Scan
    - name: Official SonarQube Scan  
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
          
